project_dir: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/
sample_table: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/sample_table.txt
scratch_dir: /tmp/tannerj
output_dir: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/output

reference_params:
    GRCh38:
        ref_name: GRCh38
        fasta: /oak/stanford/groups/euan/annotations/homo_sapiens/GRCH38/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta
    GRCh37:
        ref_name: GRCh37
        fasta: /oak/stanford/groups/euan/annotations/homo_sapiens/GRCH37/reference/GRCh37.fa

PAR_bed:
  GRCh38: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/annotation/GRCh38_PAR.bed
  GRCh37: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/annotation/GRCh37_PAR.bed

TRF_annotation:
  GRCh38: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/annotation/human_GRCh38_no_alt_analysis_set.trf.bed
  GRCh37: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/annotation/human_hs37d5.trf.bed

SV_truth_set:
  GRCh38: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/truth_sets/HG002_GRCh38_difficult_medical_gene_SV_benchmark_v0.01.vcf.gz
  GRCh37: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/truth_sets/GRCh37.GIAB_INDEL_SV_benchmark.HG002_SVs_Tier1_v0.6.vcf.gz

SV_truth_bed:
  GRCh38: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/truth_sets/HG002_GRCh38_difficult_medical_gene_SV_benchmark_v0.01.bed
  GRCh37: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/truth_sets/GRCh37.GIAB_INDEL_SV_benchmark.HG002_SVs_Tier1_v0.6.bed

phasing_truth_set:
  GRCh38: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/truth_sets/HG002_GRCh38_1_22_v4.2.1_benchmark_phased_MHCassembly_StrandSeqANDTrio.vcf.gz

smallvar_truth_set:
  GRCh38: 
    CMRG: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/truth_sets/HG002_GRCh38_difficult_medical_gene_smallvar_benchmark_v0.02.03.vcf.gz
    NISTv4.2: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/truth_sets/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz

smallvar_truth_bed:
  GRCh38: 
    CMRG: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/truth_sets/HG002_GRCh38_difficult_medical_gene_smallvar_benchmark_v0.02.03.bed
    NISTv4.2: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/truth_sets/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed


smallvar_vcf:
  GRCh38:
    ICLR: /oak/stanford/groups/euan/projects/john_primate/ICLR_HG002/grch38_vcf/Unmarked_Sample_611773165.Marked_Sample_640456819.combined_iclr_sbs.phased.vcf.gz
    ONT_duplex: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/output/whatshap/ONT_duplex.GRCh38.deep_variant.small_vars.whatshap_PHASED.vcf.gz
    PacBio_Revio: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/output/whatshap/PacBio_Revio.GRCh38.deep_variant.small_vars.whatshap_PHASED.vcf.gz

SV_vcf:
  GRCh38:
    sniffles:
      ICLR: /oak/stanford/groups/euan/projects/john_primate/ICLR_HG002/grch38_vcf/Unmarked_Sample_611773165.Marked_Sample_640456819.combined_iclr_sbs.sv.vcf.gz
      ONT_duplex: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/output/SV_calls/ONT_duplex/GRCh38/sniffles/ONT_duplex.GRCh38.SVs.sniffles.vcf.gz
      PacBio_Revio: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/output/SV_calls/PacBio_Revio/GRCh38/sniffles/PacBio_Revio.GRCh38.SVs.sniffles.vcf.gz
  GRCh37:
    sniffles:
      ICLR: /oak/stanford/groups/euan/projects/john_primate/ICLR_HG002/grch37_vcf/Unmarked_Sample_611773165.Marked_Sample_640456819.combined_iclr_sbs.sv.vcf.gz
      ONT_duplex: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/output/SV_calls/ONT_duplex/GRCh37/sniffles/ONT_duplex.GRCh37.SVs.sniffles.vcf.gz
      PacBio_Revio: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/output/SV_calls/PacBio_Revio/GRCh37/sniffles/PacBio_Revio.GRCh37.SVs.sniffles.vcf.gz

phased_alignments:
  GRCh38:
    ICLR: /oak/stanford/groups/euan/projects/john_primate/ICLR_HG002/grch38_vcf/Unmarked_Sample_611773165.bam
    ONT_duplex: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/output/alignment/ONT_duplex.GRCh38.sorted.whatshap_PHASED.bam
    PacBio_Revio: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/output/alignment/PacBio_Revio.GRCh38.sorted.whatshap_PHASED.bam


TR_repeat_catalog:
  GRCh38: /oak/stanford/groups/euan/projects/tannerj/UDN/references/adotto_repeats.hg38.bed.gz

vamos_repeat_catalog:
  GRCh38: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/truth_sets/Adotto_TR_reference.vamos.bed

trgt_bin: /oak/stanford/groups/smontgom/tannerj/SeqTech_SVcalling_Benchmark/HG002_GIAB/scripts/trgt-v0.8.0-linux_x86_64
